[workspace]
members = [
    "mystiko_config",
    "mystiko_config_uploader",
    "mystiko_relayer_abi",
    "mystiko_relayer_config",
    "mystiko_types",
    "mystiko_validator",
]
resolver = "2"

exclude = []